---
- name: Create a directory
  file:
    path: "{{ web_docker_path }}"
    state: directory
    owner: server
    group: server
    mode: 0755

- name: Copy the required files to run web server
  copy:
    src: roles/webserver1/files/
    dest: "{{ web_docker_path }}"
    owner: server
    group: server
    mode: 0644

- name: Change permission for docker-entrypoint script
  file:
    path: "{{ web_docker_path }}/joomla-php/docker-entrypoint.sh"
    owner: server
    group: server
    mode: 0755

- name: Build docker images and run containers using docker-compose
  shell:
    chdir: "{{ web_docker_path }}/docker-compose"
    cmd: docker-compose up -d