---
- name: fetch all public ssh keys
  shell: cat ~/.ssh/id_rsa.pub
  register: ssh_keys
  tags:
    - ssh

- name: check keys
  debug: msg="{{ ssh_keys.stdout }}"
  tags:
    - ssh

- name: deploy keys on all servers
  authorized_key: user=server key="{{ item[0] }}"
  delegate_to: "{{ item[1] }}"
  with_nested:
    - "{{ ssh_keys.stdout }}"
    - "{{groups['all_webservers']}}"
  tags:
    - ssh

- name: Install EPEL repository
  become: yes
  yum:
    name: epel-release
    state: present

- name: Install Unison
  become: yes
  yum:
    name: unison
    state: present

- name: Create a directory for Unison
  file:
    path: "{{ unison_dir }}"
    state: directory
    owner: server
    group: server
    mode: 0755

- name: Copy the default file for Unison in webserver-1
  copy:
    src: roles/unison/files/web1/
    dest: "{{ unison_dir }}"
    owner: server
    group: server
    mode: 0644
  delegate_to: "{{groups['all_webservers'][0]}}"

- name: Copy the default file for Unison in webserver-2
  copy:
    src: roles/unison/files/web2/
    dest: "{{ unison_dir }}"
    owner: server
    group: server
    mode: 0644
  delegate_to: "{{groups['all_webservers'][1]}}"

- name: Run Unison automatically using cronjob
  cron:
    name: Run Unison
    job: for i in {1..6}; do /usr/bin/unison & sleep 10; done
    state: present