---
- name: Setting up SSH service
  hosts: all
  gather_facts: false
  roles:
    - ssh

- name: Setting up Docker and Docker Compose
  hosts: loadbalancer,all_webservers
  gather_facts: false
  roles:
    - docker

- name: Setting up database and replication
  hosts: all_dbservers
  gather_facts: false
  roles:
    - postgres-pgpool

- name: Setting up Webservers
  hosts: all_webservers
  gather_facts: false
  roles:
    - webserver

- name: Setting up Unison
  hosts: all_webservers
  gather_facts: false
  roles:
    - unison

- name: Setting up Load balancer
  hosts: loadbalancer
  gather_facts: false
  roles:
    - haproxy

- name: Setting up newrelic infrastructure monitoring
  hosts: all
  gather_facts: false
  roles:
    - newrelic-infra