---
- name: Generate SSH key
  hosts: webservers
  roles:
    - ssh-generate

- name: Distribute control-node's SSH public key to remote servers
  hosts: webservers
  roles:
    - ssh-copy

- name: Setting up Docker and Docker Compose
  hosts: webservers
  roles:
    - docker

- name: Setting up Webserver-1
  hosts: webserver1
  roles:
    - webserver1

- name: Setting up Webserver-2
  hosts: webserver2
  roles:
    - webserver2

- name: Setting up Unison
  hosts: webservers
  roles:
    - unison