version: '3.7'

services:
  nginx:
    build:
      context: ../nginx/
    image: nginx-alpine
    container_name: nginx-container-web2
    restart: always
    ports:
      - 80:80
    volumes:
      - ./joomla:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - joomla_with_newrelic

  joomla_with_newrelic:
    build:
      context: ../joomla-php/
    image: joomla-alpine
    container_name: joomla-container-web2
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./joomla:/var/www/html
      - ./configuration.php:/var/www/html/configuration.php

#  newrelic-php-daemon:
#    container_name: neo-newrelic-php-daemon
#    image: newrelic/php-daemon
#    restart: always

networks:
  default:
    name: webserver_network
